name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.x'
          channel: 'stable'
      
      - name: Enable Flutter Web
        run: flutter config --enable-web
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build Web
        run: flutter build web --base-href /
      
      - name: Create .nojekyll file
        run: touch build/web/.nojekyll
      
      # Nếu có CNAME, sao chép vào thư mục build
      - name: Copy CNAME
        run: cp -f CNAME build/web/ || echo "No CNAME file found"
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true